[package]
name = "lc3"
version = "0.1.0"
authors = ["Odin Dutton <odindutton@gmail.com>"]
edition="2018"

[dependencies]
byteorder = "1"
termios = "0.3"
regex = "1"
lazy_static = "1.2.0"
libc = "0.2"
resp = "1"
nix = "0.13"
